config/routes.rb
Rails.application.routes.draw do
  resources :linguagens
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "pagina_principal#index"

  get 'sobre', to: 'pagina_principal#sobre'

  get 'linguagens', to: 'linguagens#index'

  get 'linguagens/new', to: 'linguagens#new'
  post 'linguagens/new', to: 'linguagens#create'

  get 'linguagens/show', to: 'linguagens#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/linguagem.rb
class Linguagem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/linguagens_controller.rb
class LinguagensController < ApplicationController
  before_action :set_linguagem, only: [:show, :edit, :update, :destroy]

  # GET /linguagens
  # GET /linguagens.json
  def index
    @linguagens = Linguagem.all
  end

  # GET /linguagens/1
  # GET /linguagens/1.json
  def show
  end

  # GET /linguagens/new
  def new
    @linguagem = Linguagem.new
  end

  # GET /linguagens/1/edit
  def edit
  end

  # POST /linguagens
  # POST /linguagens.json
  def create
    @linguagem = Linguagem.new(linguagem_params)

    respond_to do |format|
      if @linguagem.save
        format.html { redirect_to @linguagem, notice: 'Linguagem was successfully created.' }
        format.json { render :show, status: :created, location: @linguagem }
      else
        format.html { render :new }
        format.json { render json: @linguagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /linguagens/1
  # PATCH/PUT /linguagens/1.json
  def update
    respond_to do |format|
      if @linguagem.update(linguagem_params)
        format.html { redirect_to @linguagem, notice: 'Linguagem was successfully updated.' }
        format.json { render :show, status: :ok, location: @linguagem }
      else
        format.html { render :edit }
        format.json { render json: @linguagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linguagens/1
  # DELETE /linguagens/1.json
  def destroy
    @linguagem.destroy
    respond_to do |format|
      format.html { redirect_to linguagens_url, notice: 'Linguagem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linguagem
      @linguagem = Linguagem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def linguagem_params
      params.require(:linguagem).permit(:nome, :extensao, :descricao, :icone)
    end
end

app/controllers/pagina_principal_controller.rb
class PaginaPrincipalController < ApplicationController
    def index
        render 'index'
    end

    def sobre
        render 'sobre'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/linguagens_helper.rb
module LinguagensHelper
end

app/helpers/pagina_principal_helper.rb
module PaginaPrincipalHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AplicacaoTeste</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Lista de Linguagens</h1>
    
    <hr>
    <%= yield %>
    
    <hr>

    <%= link_to "Pagina Incial", root_url %>
  </body>
</html>

app/views/linguagens/_form.html.erb
<%= form_with(model: linguagem, local: true) do |form| %>
  <% if linguagem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(linguagem.errors.count, "error") %> prohibited this linguagem from being saved:</h2>

      <ul>
        <% linguagem.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :extensao %>
    <%= form.text_field :extensao %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :icone %>
    <%= form.text_field :icone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/linguagens/edit.html.erb
<h1>Editing Linguagem</h1>

<%= render 'form', linguagem: @linguagem %>

<%= link_to 'Show', @linguagem %> |
<%= link_to 'Back', linguagens_path %>

app/views/linguagens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Linguagens</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Extensao</th>
      <th>Descricao</th>
      <th>Icone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @linguagens.each do |linguagem| %>
      <tr>
        <td><%= linguagem.nome %></td>
        <td><%= linguagem.extensao %></td>
        <td><%= linguagem.descricao %></td>
        <td><%= linguagem.icone %></td>
        <td><%= link_to 'Show', linguagem %></td>
        <td><%= link_to 'Edit', edit_linguagem_path(linguagem) %></td>
        <td><%= link_to 'Destroy', linguagem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Linguagem', new_linguagem_path %>

app/views/linguagens/new.html.erb
<%= link_to "Voltar para Lista de Linguagens", linguagens_path%>
<br><br>

<%=  render 'forms', linguagem: @linguagem %>

app/views/linguagens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @linguagem.nome %>
</p>

<p>
  <strong>Extensao:</strong>
  <%= @linguagem.extensao %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @linguagem.descricao %>
</p>

<p>
  <strong>Icone:</strong>
  <%= @linguagem.icone %>
</p>

<%= link_to 'Edit', edit_linguagem_path(@linguagem) %> |
<%= link_to 'Back', linguagens_path %>

app/views/pagina_principal/index.html.erb
<div id="index">
    <div>
    <h2>Bem Vindo ao nosso site.</h2>

    <p>
        <i>A luta diaria só cria guerreiros mais fortes</i>
    </p>
    </div>

    <div id="app"></div>
</div>

app/views/pagina_principal/sobre.html.erb
<%= javascript_pack_tag 'hello_react' %>
<script>

document.addEventListener('DOMContentLoaded', () => {
  ReactDOM.render(
    <Hello name="React" idade={5} />,
    document.getElementById('app'),
  )
})

</script>
<div id="app"></div>